# .github/workflows/sync-detection-rules.yml
name: Sync Detection Rules

on:
  schedule:
    - cron: '0 * * * *'  # Hourly sync
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # --- SlimKQL (main branch) ---
      - name: Sync SlimKQL rules
        run: |
          mkdir -p synced/SlimKQL
          git clone --depth=1 https://github.com/SlimKQL/Hunting-Queries-Detection-Rules.git slimkql-tmp
          rsync -a --delete slimkql-tmp/ synced/SlimKQL/
          rm -rf slimkql-tmp

      # --- Yamato (hayabusa-rules/sigma subdirectory) ---
      - name: Sync Yamato rules
        run: |
          mkdir -p synced/Yamato
          git clone --filter=blob:none --depth=1 https://github.com/Yamato-Security/hayabusa-rules.git yamato-tmp
          rsync -a --delete yamato-tmp/sigma/ synced/Yamato/
          rm -rf yamato-tmp

      # --- Elastic (standard sync) ---
      - name: Sync Elastic rules
        run: |
          mkdir -p synced/Elastic
          git clone --depth=1 https://github.com/elastic/detection-rules.git elastic-tmp
          rsync -a --delete elastic-tmp/rules/ synced/Elastic/
          rm -rf elastic-tmp

      # --- Sigma (standard sync) ---
      - name: Sync Sigma rules
        run: |
          mkdir -p synced/Sigma
          git clone --depth=1 https://github.com/SigmaHQ/sigma.git sigma-tmp
          rsync -a --delete sigma-tmp/rules/ synced/Sigma/
          rm -rf sigma-tmp

      # --- Sublime (detection-rules subdirectory) ---
      - name: Sync Sublime rules
        run: |
          mkdir -p synced/Sublime
          git clone --depth=1 https://github.com/sublime-security/sublime-rules.git sublime-tmp
          rsync -a --delete sublime-tmp/detection-rules/ synced/Sublime/
          rm -rf sublime-tmp

      # --- Verification ---
      - name: Verify synced content
        run: |
          echo "Synced content:"
          find synced/ -type f | head -n 20
          du -sh synced/*

      # --- Commit Changes ---
      - name: Commit and push changes
        run: |
          git add synced/
          if git diff --cached --quiet; then
            echo "No changes detected"
            exit 0
          fi
          git commit -m "chore: sync detection rules [automated]"
          git push
